<div class="auth-body">
<div class="auth-form">
	<div class="col-lg-12 col-md-12 col-sm-12 col-centered">
		<div class="col-lg-8 col-md-8 col-sm-8 col-centered">
			<div class="validate"><?php print_r(core\validator::displayErrors($errors));?></div>
			<form id="" method="post" action="/account/login" class="form-horizontal no-border">
			<p class="article-title"><?php echo $this->app->getAppTitle();?></p>	
			<h1 class="article-title">Sign in</h1>	
				<div class="form-group">
					<div class="col-lg-12 col-md-12 col-sm-12 no-pad-row">
						<label for="username">Username</label>
						<input type="text" id="username" name="username" class="form-control" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-lg-12 col-md-12 col-sm-12 no-pad-row">
						<label for="password">Username</label>
						<input type="password" id="password" name="password" class="form-control" />
					</div>
				</div>
				<br />
				<div class="form-group">
					<div class="col-lg-12 col-md-12 col-sm-12 no-pad-row">
					<input type="submit" id="lgusr" name="lgusr" value="Sign In" class="btn btn-custom btn-sm" />
					</div>
				</div>

				<div class="auth-footer">
					<p><a href="#">Can't access your acount?</a></p>
				</div>
			</form>
		</div>
	</div>
</div>
</div>
