<div class="col-md-12">
	<h1 class="jumbo">Change Password</h1>
</div>


<form id="edit" action="/user/password/<?php echo $user['userID'];?>" method="post" class="proc form-horizontal">
    
	<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="form-header">Change User Password
				<span class="pull-right">
					<a id="listed_<?php echo $user['userID']; ?>" class="partial" href="/user/details/<?php echo $user['userID']; ?>">Details</a>
				</span>
			</div>
		</div>
	</div>
	
		<div class="validate"><?php print_r(core\validator::displayErrors($errors));?></div>
	
			<div><input type="hidden" id="userID" name="userID" value="<?php echo $user['userID'];?>" /></div>
			<div class="form-group">
				<div class="col-lg-5 col-md-5 col-sm-5 no-pad-row">
					<label for="names">Name</label>
					<input type="text" id="names" name="names" readonly value="<?php echo $user['names'];?>" class="form-control input-sm" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-lg-3 col-md-3 col-sm-3 no-pad-row">
					<label for="username">Username</label>
					<input type="text" id="username" name="username" readonly value="<?php echo $user['username'];?>" class="form-control input-sm" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-lg-3 col-md-3 col-sm-3 no-pad-row">
					<label for="password">Password</label>
					<input type="password" id="password" name="password" class="form-control input-sm" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-lg-3 col-md-3 col-sm-3 no-pad-row">
					<label for="confirmpassword">Confirm Password</label>
					<input type="password" id="confirmpassword" name="confirmpassword" class="form-control input-sm" />
				</div>
			</div>
			<br />
			<div class="row">
				  <div class="form-group">
					  <div class="col-lg-10 col-md-10 col-sm-10">
						  <input type="submit" id="pasusr" name="pasusr" class="btn btn-custom btn-sm" value="Change Password" />
					  </div>
				  </div>
			  </div>
	</form>
	
	
			